/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.ts to modify the generation of this file.
const config = {};
config.sitecoreApiKey = process.env.SITECORE_API_KEY || "{4672EB7C-E577-43CC-8B6C-EA04611866A8}",
config.sitecoreApiHost = process.env.SITECORE_API_HOST || "https://sc103sc.dev.local",
config.jssAppName = process.env.JSS_APP_NAME || "job-site-app",
config.graphQLEndpointPath = process.env.GRAPH_QL_ENDPOINT_PATH || "/sitecore/api/graph/edge",
config.graphQLEndpoint = process.env.GRAPH_QL_ENDPOINT || `${config.sitecoreApiHost}${config.graphQLEndpointPath}`;
module.exports = config;